PS C:\Git\HatchTestSelection> hatch new --init
Project name: hatchtestselection
Description []: Demonstrates selecting alternate file and function names for Pytest within Hatch

Wrote: pyproject.toml
PS C:\Git\HatchTestSelection> hatch shell
  error: subprocess-exited-with-error

  Preparing editable metadata (pyproject.toml) did not run successfully.
  exit code: 1

  [26 lines of output]
  Traceback (most recent call last):
    File "C:\Users\Bruce\AppData\Local\hatch\env\virtual\hatchtestselection\ALDqKaZQ\hatchtestselection\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "C:\Users\Bruce\AppData\Local\hatch\env\virtual\hatchtestselection\ALDqKaZQ\hatchtestselection\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Bruce\AppData\Local\hatch\env\virtual\hatchtestselection\ALDqKaZQ\hatchtestselection\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 186, in prepare_metadata_for_build_editable
      whl_basename = build_hook(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Bruce\AppData\Local\Temp\pip-build-env-b_bp5_qo\overlay\Lib\site-packages\hatchling\build.py", line 78, in build_editable
      return os.path.basename(next(builder.build(wheel_directory, ['editable'])))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Bruce\AppData\Local\Temp\pip-build-env-b_bp5_qo\overlay\Lib\site-packages\hatchling\builders\plugin\interface.py", line 93, in build
      self.metadata.validate_fields()
    File "C:\Users\Bruce\AppData\Local\Temp\pip-build-env-b_bp5_qo\overlay\Lib\site-packages\hatchling\metadata\core.py", line 242, in validate_fields
      _ = self.version
          ^^^^^^^^^^^^
    File "C:\Users\Bruce\AppData\Local\Temp\pip-build-env-b_bp5_qo\overlay\Lib\site-packages\hatchling\metadata\core.py", line 128, in version
      self._version = self._get_version()
                      ^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Bruce\AppData\Local\Temp\pip-build-env-b_bp5_qo\overlay\Lib\site-packages\hatchling\metadata\core.py", line 225, in _get_version
      version = self.hatch.version.cached
                ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Bruce\AppData\Local\Temp\pip-build-env-b_bp5_qo\overlay\Lib\site-packages\hatchling\metadata\core.py", line 1413, in cached
      raise type(e)(message) from None
  OSError: Error getting the version from source `regex`: file does not exist: hatchtestselection/__about__.py
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
PS C:\Git\HatchTestSelection> hatch env create
Environment `default` already exists
PS C:\Git\HatchTestSelection> hatch shell
You are about to enter a new shell, exit as you usually would e.g. by typing `exit` or pressing `ctrl+d`...
(hatchtestselection) PS C:\Git\HatchTestSelection> pytest
[pytest command worked]
